---
- name: Examen Networkautomation - vraag2.
  hosts: howestnode

  tasks:

    - name: Install Fish shell.
      ansible.builtin.apt:
        name: fish
        update_cache: true

    - name: Make sure Johnny Megatron user is present
      ansible.builtin.user:
        name: Johnny
        group: sudo
        shell: /usr/bin/fish
        state: present
        password: "{{ 'Test123' | password_hash('sha512', 'mysecretsalt') }}"
        update_password: on_create
        comment: Johnny Megatron

    - name: Get Alt text from XKCD.
      ansible.builtin.uri:
        url: https://xkcd.com/info.0.json
      register: xkcd

    - name: Put XKCD in MOTD.
      ansible.builtin.copy:
        dest: /etc/motd
        content: " {{ xkcd.json.alt }}"

    - name: Install prerequisites Minesweeper.
      ansible.builtin.apt:
        name: 
          - build-essential
          - git
        state: present
        update_cache: true

    - name: Clone Minesweeper repo.
      ansible.builtin.git:
        dest: /usr/bin/Minesweeper
        repo: https://github.com/unknownblueguy6/MineSweeper.git

    - name: Make Mineseeper file
      community.general.make:
        chdir: /usr/bin/Minesweeper

    - name: Add "Mine" as alias for Mineseeper program for user "Johnny".
      ansible.builtin.lineinfile:
        path: /home/Johnny/.config/fish/config.fish
        line: 'alias mine="/usr/bin/Minesweeper/mine"'
        state: present
        create: true
